### ISSUE TITLE
Spa Shows as 32F, When Not On

### ISSUE THREAD

**Issue by arrmo** [gadget-monk/homebridge-poolcontroller#5]
Hi,

When my pool is in "pool mode", and the spa shows as off ... the spa temperature is being set / interpreted as 32F (as it's not reported, even though my pool flows through my spa).

Would it make sense to have an option, set the spa temp to be the same as the pool, when the spa is off?

Thanks!

**Comment by gadget-monk** [comment]
Hi! The plug in copies down the water temps from njspc. The 32F reading is because there is no valid temp to report. Once you run the the spa, njspc will start caching the last reported temp from the spa and provide it to the plugin.

**Comment by arrmo** [comment]
Makes sense, thanks! FYI, have been working with njsPC, as there was a missing temp (needing it for influxdb processing). A recent update there, so now a couple observations. Please let me know your thoughts.
1) I have 2 watersensor items (1 and 2) ... but they match to the body objects (pool and spa). So ignore / remove the watersensor fields, and just pull temp from the bodies (as reported in the API by /state/all)?
2) Within HomeKit, items look very good - just a couple minor items in the temperatures,
a) Air Temperature - is perfect!
b) Pool ... temp is right, but the state is incorrect (i.e. shows Off, when On?)
c) Spa ... temp is right (matching njsPC) but the state is incorrect (shows On, when Off?)
b) Water Sensor - remove, rather just use the temperatures in the bodies (which are correct, as above)? There is only 1, when there could be 2, but in any case remove it/them?
3) Also in HomeKit, the temperature "indicator" (circle, near the top left) shows "Idle" even when (the pool is) on. Should this match the state (i.e. if either is on, then say On)?

Thanks!

**Comment by gadget-monk** [comment]
1. The water sensor is duplicative with the thermostat in the water body objects. The only reason I added both a sensor and the thermostat is because when the heater is turned on, the HomeKit display shows the target temp only and not the current temp, and I wanted a way to quickly see the current temp on Apple Watch. I don't know if iOS 14 changed things since I haven't turned on the heater after upgrading. I have only one sensor so I may have buggy code when there are two sensors. Let me know if the sensors report correct temps. 

2. Are you referring to the state of the water body (shown as a switch) or the thermostat mode (circle below the thermostat display)? The thermostat mode switches between "Auto" and "Heat off"? 

I see your comments on njsPC about using influx... have you taken a look at the HomeKit based history logging built into this plugin? Install the Eve app from App Store and you will history data for temps and pump power consumption. I am planning to add history for switches as well (hopefully will get some time to work on an update over thanksgiving).

**Comment by arrmo** [comment]
1. I think (may be wrong!) that both temps are showing up (target and actual). Is the issue mainly / only on Apple Watch, or also iPhone? Asking as I can check here, let you know.

2. OK, you lost me there ... LOL. I'm meaning the screen that opens up after selecting the "temperature circle". Does that make sense?

History logging? No, I admit - I missed that. Is it in the Homebridge web interface (ui-x)? I do see some info in Eve, stumbled across that earlier today actually. It is very cool! Is Eve meant to be linked closed to Homebridge? Sorry, I'm dumb about that - my bad.

Thanks!

**Comment by gadget-monk** [comment]
Only talking from memory here. I think the issue was on both devices. On the watch the thermostat doesn't how any temps (current or target). Either way not a big deal, I can just add a config option to suppress the water temp sensors. 

Lol, I am lost too. Can you post a screenshot? 

History logging is in the Eve app not UI-x. Once you install the app, it will automatically load all the accessories from the Home app and display additional characteristics for supported accessories. Here is a screenshot of the air temp history and pump power consumption:
![IMG_9553957807D4-1](https://user-images.githubusercontent.com/20653026/100181076-5fa7d380-2e8e-11eb-941f-483ceb064edc.jpeg)
![IMG_444A251DB645-1](https://user-images.githubusercontent.com/20653026/100181087-633b5a80-2e8e-11eb-9bee-9446e3c2178a.jpeg)

**Comment by arrmo** [comment]
> Lol, I am lost too. Can you post a screenshot?

Sure - below, with an explation of the state, trying to walk through what I checked here (take care of phone first, then look at the watch?). BTW, I screwed up, big time! Most important, I do want to say thanks so much. This really is very cool, works great. What I'm mentioning is minor / nitpicky, want you to know that!

Here is what I tried (BTW, ignore Switch 1 and 2 - they are not part of the pool itself, but in that room ... plugged in to the same outlet, for my Christmas lights 😆).
1) Pool mode, on and running. See the "Idle" circle right below "Pool"? Thinking that should say "On" (or something like that) when the pool or spa is running?
![IMG_0728](https://user-images.githubusercontent.com/8756384/100249100-cfa37180-2f01-11eb-982e-32ec3a008f70.PNG)
2) Selecting that Idle circle, to see the temps ... it shows the Spa as on (bright), Pool as off - but from 1) above, you can see that the pool is on, spa is off. Thinking this should be the other way around then (Pool on and bright, Spa off?). Or, show the pool as Off (as this is the heat mode, that makes sense), but make sure the state (bright / dim) is correct?
![IMG_0729](https://user-images.githubusercontent.com/8756384/100249244-f661a800-2f01-11eb-95d3-40acbf71f0f5.PNG)
3) Kicked the Spa on, as shown ... but still says Idle?
![IMG_0730](https://user-images.githubusercontent.com/8756384/100249460-332d9f00-2f02-11eb-8b00-75203e29db93.PNG)
4) And again, the Idle circle selected - you can see, the Spa shows the setpoint and temperature both (so the Water Sensor can be hidden / not used?).
![IMG_0731](https://user-images.githubusercontent.com/8756384/100249497-3e80ca80-2f02-11eb-8006-0af06b96a9c6.PNG)

Sort of make more sense now? :wink:. Just let me know your thoughts.

And again - sincere thanks!!!

**Comment by gadget-monk** [comment]
Ah, I get it now. The white circle around the spa indicates that the heat mode is set to "Auto". The status of the spa or pool circuit is indicated by the switch accessory. I believe the idle state changes to say "heating" when the heater actually starts up.

**Comment by arrmo** [comment]
Ahh, OK - so the white color in the temperature "sub-screen" indicates the heating mode, not on/off ... right?

Would it still make sense to have the option to hide the Water Sensor, as it's copied to Pool and/or Spa (depending on operating mode)?

Thanks!

**Comment by arrmo** [comment]
BTW, not sure if you see this or not, but to your comments about Eve (which is really cool!) - I see data under Water Sensor, but not Pool or Spa. Is that expected?

And for aging eyes ... 😆. Is there web access to Eve (and those graphs)?

Thanks!

**Comment by gadget-monk** [comment]
Makes sense to disable the water sensor - I can add a config option. 
On Eve - unfortunately I don't know about a way to access the graphs via web. Pool and Spa temps should have graphs too (under Target Temperature).

**Comment by gadget-monk** [comment]
Uploaded new version with config option... try it out and let me know if it works!

**Comment by arrmo** [comment]
Thanks so much - really appreciated! I updated the plugin, enabed the option (I see now, "SupressWaterSensor": true,) ... but the Water Sensor is still there. Is it that it won't create a new one, but somehow the existing one has to be deleted?



> Pool and Spa temps should have graphs too (under Target Temperature).

Got it - my bad, was looking the wrong place. Thanks! Odd though, it now shows no data for 3 days. Hmmm.

**Comment by gadget-monk** [comment]
That’s probably because the old water sensor accessory is cached by homebridge. Easiest way is to delete the plugin including config and restart homebridge so all cached accessories are deleted, then reinstall the plugin. 

The gap in history is odd, maybe plugin reinstall will fix it.

**Comment by arrmo** [comment]
That was it (cache), thanks!

Will let you know on the temperature data.

**Comment by arrmo** [comment]
Nope, no data for 4 days. Wondering how I screwed it up 😜.

BTW, just curious, but ... why is it "target" temperature? No biggie.

Thanks!

**Comment by gadget-monk** [comment]
It’s probably something connected with the recent changes I made to add history logging for all circuits. I will take another look. 

The target temp is what your heater is set to, but I don’t know why Eve shows actual temp history under Target temp. It’s odd, but unfortunately not customizable

**Comment by arrmo** [comment]
> It’s probably something connected with the recent changes I made to add history logging for all circuits. I will take another look.

Thanks, appreciate it!

> Target temp. It’s odd, but unfortunately not customizable

Understood, and no biggie.

**Comment by arrmo** [comment]
Hi,

Any luck checking on the data (not going to Eve)? Or do you not see the same thing?

Thanks!

**Comment by gadget-monk** [comment]
I see the problem. The only fix is to have separate accessories for the "switch" and thermostat instead of combined one like I used to earlier. This results in a small change in how the body accessory shows up in home.app, but seems to work better. Doing a bit more testing and then push an update out.

**Comment by arrmo** [comment]
No worries - and no panic. Wanted to see if I was losing in 🤣. Thanks!

**Comment by gadget-monk** [comment]
pushed out a new version, can you try and see if it works?

**Comment by arrmo** [comment]
Updated, waited for a bit (to see data getting to Eve). Seems to be working just fine now, thanks!

You mentioned a "small change in how the body accessory shows up in home.app"?

**Comment by gadget-monk** [comment]
Yes, earlier there was one tile for Pool and Spa that has an on/off switch and a thermostat, in the new version there are two separate tiles

**Comment by arrmo** [comment]
Ummm ... mine still shows tile(s) with the switch and thermostat. You no longer see that?

**Comment by gadget-monk** [comment]
its probably the same cached accessories issue from earlier. Remove the plugin and restart hb and reinstall plugin to clear cache.

**Comment by arrmo** [comment]
But I like it this way ... LOL. Will do, thanks!

**Comment by gadget-monk** [comment]
Lol... me too, but I can’t get history logging to work with a switch and Thermo.

**Comment by gadget-monk** [comment]
Everything working ok after the updates? Can we close this issue?

**Comment by arrmo** [comment]
Working great, thanks!!!

Sorry, I should have closed it - my bad. Closing now.
